name: cab_driver
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase_database: ^4.0.0
  connectivity: ^0.4.9+3
  google_maps_flutter: ^1.0.2
  outline_material_icons: ^0.1.1
  geolocator: ^6.0.0+4
  location: ^3.0.0
  http: ^0.12.2
  provider: ^4.3.2+2
  flutter_polyline_points: ^0.2.4
  font_awesome_flutter: ^8.10.0
  animated_text_kit: ^2.4.0
  flutter_geofire: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assetes/images/
    - assetes/images/user_icon.png
    #   - images/a_dot_ham.jpeg



  fonts:
    - family: BoltSemi
      fonts:
        - asset: assetes/fonts/bolt-semibold.ttf
      #         style: italic
    - family: BoltRegular
      fonts:
        - asset: assetes/fonts/bolt-regular.ttf
    #       - asset: fonts/TrajanPro_Bold.ttf
    #         weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
